repos:
-   repo: local
    hooks:
    -   id: create-jekyll-tags
        name: create-jekyll-tags
        entry: python scripts/create_jekyll_tag_stubs.py
        language: python
        files: _posts/.*

