# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Zachary Levonian's blog
email: zacharylevonian@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Zachary Levonian's blog, for self-published writing.
  Zach is a researcher and data scientist with a PhD in Human-computer Interaction.
domain: levon003.github.io
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://levon003.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: zwlevonian
github_username:  levon003
linkedin_username: zachary-levonian-376b56a0
mastodon:
 - username: zwlevonian
   instance: hci.social
show_excerpts: true

# Build settings
theme: minima
plugins:
  - jekyll-feed

# these pages will appear in the header
header_pages:
 - blog_index.markdown

# these are front-matter YAML defaults
defaults:
  - 
    scope:
      path: ""
      type: "posts"
    values:
      author: "Zachary Levonian"
      author_link: "/blog"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
